#version: "3.8"
version: "3.3"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:1.8.16
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    image: quarkus/code-with-quarkus-fast-jar
    depends_on:
      - "db"
    build:
      context: api
      dockerfile: api/src/main/docker/Dockerfile.fast-jar
    ports:
      - "8080:8080"
    restart: "on-failure"
  front:
    image: aamiard/tlcfront
    depends_on:
      - "api"
    build:
      context: front
      dockerfile: front/Dockerfile
    ports:
      - "90:80"
